package com.deepesh.resumeai.controller;

import com.deepesh.resumeai.service.PdfReportService;
import com.fasterxml.jackson.databind.JsonNode;
import org.springframework.http.ContentDisposition;
import org.springframework.http.HttpHeaders;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

@RestController
@RequestMapping("/api/reports")
public class PdfExportController {

        private final PdfReportService pdfReportService;

        public PdfExportController(PdfReportService pdfReportService) {
                this.pdfReportService = pdfReportService;
        }

        @PostMapping(value = "/pdf", produces = MediaType.APPLICATION_PDF_VALUE)
        public ResponseEntity<byte[]> exportPdf(@RequestBody JsonNode analysis) {

                System.out.println("PDF EXPORT: request received");

                try {

                        byte[] pdf = pdfReportService.generateReport(analysis);

                        System.out.println("PDF EXPORT: generated bytes = " + pdf.length);

                        HttpHeaders headers = new HttpHeaders();

                        headers.setContentType(MediaType.APPLICATION_PDF);

                        headers.setContentDisposition(
                                        ContentDisposition.attachment().filename("candidate-intelligence-report.pdf").build());

                        headers.setContentLength(pdf.length);

                        return ResponseEntity.ok().headers(headers).body(pdf);

                } catch (Exception ex) {

                        System.err.println("PDF EXPORT FAILED: " + ex.getClass().getName() + " - " + ex.getMessage());

                        ex.printStackTrace();

                        throw new RuntimeException("PDF generation failed", ex);
                }
        }
}