package com.deepesh.resumeai.service;

import com.fasterxml.jackson.databind.JsonNode;
import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.pdmodel.PDPage;
import org.apache.pdfbox.pdmodel.PDPageContentStream;
import org.apache.pdfbox.pdmodel.common.PDRectangle;
import org.apache.pdfbox.pdmodel.font.PDType1Font;
import org.apache.pdfbox.pdmodel.font.Standard14Fonts;
import org.springframework.stereotype.Service;

import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;

@Service
public class PdfReportService {

        private static final float MARGIN = 50;
        private static final float PAGE_BOTTOM = 55;
        private static final float PAGE_WIDTH = PDRectangle.LETTER.getWidth();
        private static final float CONTENT_WIDTH = PAGE_WIDTH - (MARGIN * 2);

        private static final float[] NAVY = { 23f / 255f, 35f / 255f, 61f / 255f };

        private static final float[] BLUE = { 53f / 255f, 104f / 255f, 240f / 255f };

        private static final float[] BORDER = { 220f / 255f, 226f / 255f, 236f / 255f };

        private final PDType1Font regular = new PDType1Font(Standard14Fonts.FontName.HELVETICA);

        private final PDType1Font bold = new PDType1Font(Standard14Fonts.FontName.HELVETICA_BOLD);

        public byte[] generateReport(JsonNode analysis) throws IOException {

                try (PDDocument document = new PDDocument(); ByteArrayOutputStream output = new ByteArrayOutputStream()) {

                        PdfContext ctx = new PdfContext(document);

                        ctx.newPage();

                        addTitle(ctx, "Candidate Intelligence Report");

                        addSmallText(ctx, "Generated by AI Candidate Intelligence | "
                                        + LocalDateTime.now().format(DateTimeFormatter.ofPattern("MMM d, yyyy h:mm a")));

                        ctx.space(15);

                        /*
                         * Recruiter Snapshot
                         */
                        /*
                         * Recruiter Snapshot
                         */
                        addSectionTitle(ctx, "Recruiter Snapshot");

                        /*
                         * Interview Readiness Derive from Job Match when no explicit field exists.
                         */
                        String readiness = firstText(analysis, "interviewReadiness", "readiness");

                        if (readiness.isBlank()) {

                                int match = numericScore(analysis, "matchScore", "jobMatchScore", "jobMatch");

                                if (match >= 90) {
                                        readiness = "Very High";
                                } else if (match >= 80) {
                                        readiness = "High";
                                } else if (match >= 65) {
                                        readiness = "Moderate";
                                } else {
                                        readiness = "Low";
                                }
                        }

                        addScore(ctx, "Interview Readiness", readiness);

                        /*
                         * Top Strengths
                         */
                        List<String> topStrengths = firstArray(analysis, "topStrengths");

                        if (topStrengths.isEmpty()) {

                                topStrengths = firstArray(analysis, "strengths").stream().limit(3).toList();
                        }

                        addListSection(ctx, "Top Strengths", topStrengths);

                        /*
                         * Top Risks
                         */
                        List<String> topRisks = firstArray(analysis, "topRisks");

                        if (topRisks.isEmpty()) {

                                topRisks = firstArray(analysis, "criticalGaps");
                        }

                        if (topRisks.isEmpty()) {

                                topRisks = firstArray(analysis, "weaknesses");
                        }

                        addListSection(ctx, "Top Risks", topRisks.stream().limit(3).toList());

                        /*
                         * Scores
                         */
                        addSectionTitle(ctx, "Candidate Fit");

                        addScore(ctx, "Job Match", score(analysis, "matchScore", "jobMatchScore", "jobMatch"));

                        addScore(ctx, "ATS Score", score(analysis, "atsScore"));

                        addScore(ctx, "Analysis Confidence", score(analysis, "confidenceScore", "analysisConfidence"));

                        addScore(ctx, "Hiring Recommendation", firstText(analysis, "hiringRecommendation", "recommendation"));

                        /*
                         * Executive Assessment
                         */
                        addTextSection(ctx, "Executive Assessment", firstText(analysis, "executiveAssessment", "executiveSummary"));

                        /*
                         * Skills
                         */
                        addListSection(ctx, "Matched Skills", firstArray(analysis, "matchedSkills"));

                        addListSection(ctx, "Missing Skills", firstArray(analysis, "missingSkills"));

                        /*
                         * Gaps
                         */
                        addListSection(ctx, "Critical Gaps", firstArray(analysis, "criticalGaps"));

                        addListSection(ctx, "Preferred Gaps", firstArray(analysis, "preferredGaps"));

                        /*
                         * Transferable Experience
                         */
                        addListSection(ctx, "Transferable Skills", firstArray(analysis, "transferableSkills"));

                        /*
                         * Strength / Weakness
                         */
                        addListSection(ctx, "Strengths", firstArray(analysis, "strengths"));

                        addListSection(ctx, "Weaknesses", firstArray(analysis, "weaknesses"));

                        /*
                         * Explainable AI
                         */
                        addListSection(ctx, "Resume Evidence", firstArray(analysis, "resumeEvidence"));

                        /*
                         * Resume optimization
                         */
                        addListSection(ctx, "ATS Recommendations", firstArray(analysis, "atsRecommendations"));

                        /*
                         * Interview Preparation
                         */
                        addListSection(ctx, "Interview Focus Areas", firstArray(analysis, "interviewFocusAreas"));

                        addFooter(ctx);

                        ctx.closeCurrentStream();

                        document.save(output);

                        return output.toByteArray();
                }
        }

        private void addTitle(PdfContext ctx, String text) throws IOException {

                ctx.ensureSpace(48);

                ctx.stream.beginText();

                ctx.stream.setNonStrokingColor(NAVY[0], NAVY[1], NAVY[2]);

                ctx.stream.setFont(bold, 20);

                ctx.stream.newLineAtOffset(MARGIN, ctx.y);

                ctx.stream.showText(clean(text));

                ctx.stream.endText();

                ctx.stream.setNonStrokingColor(0, 0, 0);

                ctx.y -= 30;
        }

        private void addSectionTitle(PdfContext ctx, String title) throws IOException {

                ctx.ensureSpace(44);

                ctx.y -= 10;

                ctx.stream.beginText();

                ctx.stream.setNonStrokingColor(BLUE[0], BLUE[1], BLUE[2]);

                ctx.stream.setFont(bold, 13);

                ctx.stream.newLineAtOffset(MARGIN, ctx.y);

                ctx.stream.showText(clean(title));

                ctx.stream.endText();

                ctx.stream.setNonStrokingColor(0, 0, 0);

                ctx.y -= 8;

                ctx.stream.setStrokingColor(BORDER[0], BORDER[1], BORDER[2]);

                ctx.stream.moveTo(MARGIN, ctx.y);

                ctx.stream.lineTo(MARGIN + CONTENT_WIDTH, ctx.y);

                ctx.stream.stroke();

                ctx.y -= 16;
        }

        private void addSmallText(PdfContext ctx, String value) throws IOException {

                ctx.stream.beginText();
                ctx.stream.setFont(regular, 8);
                ctx.stream.newLineAtOffset(MARGIN, ctx.y);
                ctx.stream.showText(clean(value));
                ctx.stream.endText();

                ctx.y -= 14;
        }

        private void addScore(PdfContext ctx, String label, String value) throws IOException {

                if (value == null || value.isBlank()) {
                        return;
                }

                ctx.ensureSpace(30);

                ctx.stream.beginText();

                ctx.stream.setFont(bold, 10);
                ctx.stream.newLineAtOffset(MARGIN, ctx.y);

                ctx.stream.showText(clean(label + ":"));

                ctx.stream.setFont(regular, 10);

                ctx.stream.showText(" " + clean(value));

                ctx.stream.endText();

                ctx.y -= 18;
        }

        private void addTextSection(PdfContext ctx, String title, String text) throws IOException {

                if (text == null || text.isBlank()) {
                        return;
                }

                addSectionTitle(ctx, title);

                writeWrappedText(ctx, text, regular, 10, 14, false);
        }

        private void addListSection(PdfContext ctx, String title, List<String> items) throws IOException {

                if (items == null || items.isEmpty()) {
                        return;
                }

                addSectionTitle(ctx, title);

                for (String item : items) {

                        if (item == null || item.isBlank()) {
                                continue;
                        }

                        writeWrappedText(ctx, item, regular, 10, 14, true);

                        ctx.y -= 3;
                }
        }

        private void writeWrappedText(PdfContext ctx, String text, PDType1Font font, float fontSize, float leading, boolean bullet)
                        throws IOException {

                float width = PDRectangle.LETTER.getWidth() - (MARGIN * 2) - (bullet ? 15 : 0);

                List<String> lines = wrapText(clean(text), font, fontSize, width);

                boolean firstLine = true;

                for (String line : lines) {

                        ctx.ensureSpace(leading + 4);

                        ctx.stream.beginText();
                        ctx.stream.setFont(font, fontSize);

                        float offset = bullet ? MARGIN + 15 : MARGIN;

                        ctx.stream.newLineAtOffset(offset, ctx.y);

                        if (bullet && firstLine) {
                                ctx.stream.showText("- " + line);
                        } else {
                                ctx.stream.showText(line);
                        }

                        ctx.stream.endText();

                        ctx.y -= leading;

                        firstLine = false;
                }
        }

        private List<String> wrapText(String text, PDType1Font font, float fontSize, float maxWidth) throws IOException {

                List<String> lines = new ArrayList<>();

                String[] words = text.split("\\s+");

                StringBuilder current = new StringBuilder();

                for (String word : words) {

                        String candidate = current.isEmpty() ? word : current + " " + word;

                        float width = font.getStringWidth(candidate) / 1000 * fontSize;

                        if (width > maxWidth && !current.isEmpty()) {

                                lines.add(current.toString());

                                current = new StringBuilder(word);

                        } else {

                                if (!current.isEmpty()) {
                                        current.append(" ");
                                }

                                current.append(word);
                        }
                }

                if (!current.isEmpty()) {
                        lines.add(current.toString());
                }

                return lines;
        }

        private void addFooter(PdfContext ctx) throws IOException {

                ctx.ensureSpace(40);

                ctx.y -= 15;

                ctx.stream.beginText();
                ctx.stream.setFont(regular, 8);
                ctx.stream.newLineAtOffset(MARGIN, ctx.y);

                ctx.stream.showText("AI-generated candidate intelligence. Human review recommended.");

                ctx.stream.endText();
        }

        private String score(JsonNode root, String... fieldNames) {

                for (String field : fieldNames) {

                        JsonNode node = root.get(field);

                        if (node != null && !node.isNull()) {

                                if (node.isNumber()) {
                                        return node.asInt() + "%";
                                }

                                String value = node.asText("");

                                if (!value.isBlank()) {
                                        return value.contains("%") ? value : value + "%";
                                }
                        }
                }

                return "";
        }

        private int numericScore(JsonNode root, String... fieldNames) {

                for (String field : fieldNames) {
                        JsonNode node = root.get(field);
                        if (node == null || node.isNull()) {
                                continue;
                        }

                        if (node.isNumber()) {
                                return node.asInt();
                        }

                        String value = node.asText("").replace("%", "").trim();

                        try {

                                return Integer.parseInt(value);

                        } catch (NumberFormatException ignored) {
                                // Try next field.
                        }
                }

                return 0;
        }

        private String firstText(JsonNode root, String... fieldNames) {

                for (String field : fieldNames) {

                        JsonNode node = root.get(field);

                        if (node == null || node.isNull()) {
                                continue;
                        }

                        if (node.isTextual()) {
                                return node.asText();
                        }

                        /*
                         * Allows hiringRecommendation to be returned as an object in future versions.
                         */
                        if (node.isObject()) {

                                for (String inner : List.of("label", "value", "recommendation", "summary", "status")) {

                                        JsonNode innerNode = node.get(inner);

                                        if (innerNode != null && innerNode.isTextual()) {

                                                return innerNode.asText();
                                        }
                                }
                        }
                }

                return "";
        }

        private List<String> firstArray(JsonNode root, String... fieldNames) {

                for (String field : fieldNames) {

                        JsonNode node = root.get(field);

                        if (node == null || node.isNull() || !node.isArray()) {

                                continue;
                        }

                        List<String> values = new ArrayList<>();

                        for (JsonNode item : node) {

                                if (item.isTextual()) {

                                        values.add(item.asText());

                                } else if (item.isObject()) {

                                        /*
                                         * Flexible support in case future DTOs return structured recommendation
                                         * objects.
                                         */
                                        String value = firstText(item, "text", "description", "name", "skill", "recommendation",
                                                        "evidence");

                                        if (!value.isBlank()) {
                                                values.add(value);
                                        }
                                }
                        }

                        return values;
                }

                return List.of();
        }

        private String clean(String value) {

                if (value == null) {
                        return "";
                }

                String cleaned = value.replace("—", "-").replace("–", "-").replace("−", "-").replace("’", "'").replace("‘", "'")
                                .replace("“", "\"").replace("”", "\"").replace("•", "-").replace("→", "->").replace("←", "<-")
                                .replace("≥", ">=").replace("≤", "<=").replace("≈", "~").replace("×", "x").replace("…", "...")
                                .replace("\u00A0", " ").replace("\n", " ").replace("\r", " ");

                cleaned = cleaned.replaceAll("[^\\x20-\\x7E\\xA0-\\xFF]", "");

                return cleaned.replaceAll("\\s+", " ").trim();
        }

        private class PdfContext {

                private final PDDocument document;

                private PDPage page;

                private PDPageContentStream stream;

                private float y;

                private PdfContext(PDDocument document) {
                        this.document = document;
                }

                private void newPage() throws IOException {

                        closeCurrentStream();

                        page = new PDPage(PDRectangle.LETTER);

                        document.addPage(page);

                        stream = new PDPageContentStream(document, page);

                        y = PDRectangle.LETTER.getHeight() - MARGIN;
                }

                private void ensureSpace(float required) throws IOException {

                        if (y - required < PAGE_BOTTOM) {
                                newPage();
                        }
                }

                private void space(float amount) {
                        y -= amount;
                }

                private void closeCurrentStream() throws IOException {

                        if (stream != null) {
                                stream.close();
                                stream = null;
                        }
                }
        }
}